services:
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swagaudrey
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/DENVER
      - URL=audrey-final.duckdns.org
      - VALIDATION=dns
      - DNSPLUGIN=duckdns
      - DUCKDNSTOKEN=22328cc-0372-417c-9507-559b0d601f93
      - STAGING=true
    volumes:
      - /home/aptalca/appdata/swag:/config
      - ./config:config
    ports:
      - 333:443
      - 90:80
    restart: unless-stopped
