apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dep
  namespace: audrey-final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: final-api
  template:
    metadata:
      labels:
        app: final-api
    spec:
      containers:
        - name: final-api
          image: audreyinglish/frontend-final-server:${TAG}
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "4000"
            - name: DATABASE_URL
              value: "postgres://appuser:apppassword@database-svc:5432/appdb"
            - name: KEYCLOAK_ISSUER
              value: "https://auth-dev.snowse.io/realms/DevRealm"
            - name: KEYCLOAK_AUDIENCE
              value: "account"
            - name: KEYCLOAK_CLIENT_ID
              value: "audrey-chat"
            - name: KEYCLOAK_JWKS_URI
              value: "https://auth-dev.snowse.io/realms/DevRealm/protocol/openid-connect/certs"
            # AI agent proxy configuration
            - name: AGENT_BACKEND_URL
              value: "http://ai-snow.reindeer-pinecone.ts.net:9292/v1/chat/completions"
            - name: AGENT_BACKEND_API_KEY
              valueFrom:
                secretKeyRef:
                  name: agent-backend-secret
                  key: AGENT_BACKEND_API_KEY
            - name: OPENAI_MODEL
              value: "gpt-oss-120b"
